version: "3.9"
services:
  web:
    build: .
    args:
      MONGO_ATLAS_USER: ${MONGO_ATLAS_USER}
      MONGO_ATLAS_PWD: ${MONGO_ATLAS_PWD}
      MONGO_ATLAS_DB: ${MONGO_ATLAS_DB}
    ports:
      - "8080:8080"
    volumes:
      - .:/apimypharmatest
      - /apimypharmatest/node_modules
