name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTER: docker.io
  IMAGE: herlandio7/apinodemongo
  DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  MONGO_ATLAS_USER: ${{ secrets.MONGO_ATLAS_USER }}
  MONGO_ATLAS_PWD: ${{ secrets.MONGO_ATLAS_PWD }}
  MONGO_ATLAS_DB: ${{ secrets.MONGO_ATLAS_DB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
    - id: meta
      uses: docker/metadata-action@v3.6.0
      with:
        images: ${{ env.REGISTER }}/${{ env.IMAGE }}
        tags: type=sha,format=long

    - name: Build and Push container images
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: 'Create env file'
      run: |
        touch .env
        echo PORT=8080 >> .env
        echo TOKEN=123 >> .env
        echo REFRESH_TOKEN=123 >> .env
        echo USER=${MONGO_ATLAS_USER} >> .env
        echo PASS=${MONGO_ATLAS_PWD} >> .env
        echo DB=${MONGO_ATLAS_DB} >> .env
        cat .env
      env: 
        MONGO_ATLAS_USER: ${{ env.MONGO_ATLAS_USER }} 
        MONGO_ATLAS_PWD: ${{ env.MONGO_ATLAS_PWD }}
        MONGO_ATLAS_DB: ${{ env.MONGO_ATLAS_DB }} 

    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ env.HEROKU_API_KEY }}
        heroku_app_name: api-nodemongo #Must be unique in Heroku
        heroku_email: herlandio7@gmail.com
        usedocker: true